/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NammaNestPayments } from "./NammaNestPayments";
export * as factories from "./factories";
export { NammaNestPayments__factory } from "./factories/NammaNestPayments__factory";
